//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoddiTestApp.Models
{
    using System;
    using System.Collections.Generic;

    //Single Tweet model. Status ID ascends automatically. UserName is pulled from current user.
    public partial class Tweet
    {
        public int StatusID { get; set; }
        public string Note { get; set; }
        public string UserName { get; set; }
    }
}
