//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoddiTestApp.Models
{
    using System;
    using System.Collections.Generic;

    // User model.
    public partial class User
    {
        public int UserID { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
    }
}
